### PR TITLE
Some small helpers added to Message and Bot, tests

### PR DESCRIPTION
**Pull request by zhulik**
Hi again. I added small helper methods to BotAPI and Message with tests. No API breaking changes. Tests is green, fmt and golint is OK. I will change package names after your approvement

### CODE REVIEW

**Comment by zhulik** [comment]
@Syfaro ?

**Comment by Syfaro** [comment]
I don't really see the point of a `QuickSend`, because that's already a one-liner. 

`bot.Send(tgbotapi.NewMessage(chatID, "Your Message"))`

Not sure if anyone else has an opinion on this.

**Comment by zhulik** [comment]
@Syfaro you are right. QuickSend removed

**Comment by Syfaro** [comment]
Alright, should be fine to merge now.

**Comment by zhulik** [comment]
@Syfaro package name updated, you can merge it

**Pull request merged**
