### PR TITLE
Hi, there not really PR, but new vision of tgbotapi with new API

### PR DESCRIPTION
**Pull request by zhulik**
Many refactorings and DRYing, all Send* functions replaces with one Send(), Some other small changes. Tests added, 85% coverage. Everything works. Travis added.

Please, check my code. I know, that public API is changed, but it's really useful. It will be great if it possible to merge my code to upstream, but i can rename project and develop it as my own.

Package Syfaro/telegram-bot-api in my fork changed to zhulik/telegram-bot-api. I will change it back if you will merge my code.

Thanks!

ps: I want to develop some Bot framework based on it, with commands support, sessions, middlewares and so on

### CODE REVIEW

**Comment by Syfaro** [comment]
Do you happen to know how many public methods changed?
I tried updating a project I'm working on, and it only took a few seconds to make it work, so it doesn't seem like it's incredibly different. 

Only issue I can see right now is that `golint` spits out 50 things, mostly because there aren't comments on your new methods. 

Also, what was the reasoning behind removing the `tgutils` package? 

And lastly, I've been playing around with designing a bot framework, you can find it [here](https://github.com/Syfaro/finch).

**Comment by zhulik** [comment]
@Syfaro SendMessage, SendPhoto, SendDocument, SendAudio, SendVoice, SendSticker, SendVideo, SendLocation, SendChatAction is replaced with one method Send.
UpdatesChan renamed to GetUpdatesChan, BotAPI has no more Updates channel in struct. Channel will returned from GetUpdatesChan and ListenForWebhook(examples in readme and bot_test.go).  Some public methods added(Like RemoveWebhook). Anybody can update their apps in 5 minutes to use new API.

About tgutils package: i suppose, that encoding audio to correct format is not responsibility of bindings lib, furthermore it support only convertion to OGG, but telegram documentation wants mp3 for SendAudio and Ogg for SendVoice. So, i think that user should prepare audio with other tools.

About golint: i will fix it's issues tomorrow. 

My framework will be [here](https://github.com/zhulik/margelet).

**Comment by Syfaro** [comment]
Alright, cool. Not too many breaking issues, I'd love to merge it after you fix the `golint` stuff.

**Comment by zhulik** [comment]
@Syfaro Lint issues fixed

**Comment by Syfaro** [comment]
Could you fix the package names now and links in the README? 

After that, I'll merge it.

**Comment by zhulik** [comment]
@Syfaro Hey, names fixed. Please register [Travis CI](https://travis-ci.org) and add your repository to it. Also, i hardcoded some File IDs, Chat IDs, Message IDs c and test Telegram Bot Token in bot_test, so i will receive messages from tests, it is not problem for me. Bot token is for test only and has opened chat only with me. I suppose there is no security issues. 

In the future, i can replace real http requests with mocks, but not now

**Comment by Syfaro** [comment]
Registered it. 

I don't mind the hardcoded stuff, I might change it to send to me instead at some point.

**Comment by zhulik** [comment]
I think, everything is OK,  you can merge it

**Pull request merged**
