### PR TITLE
Update webhook.go

### PR DESCRIPTION
**Pull request by gobwas**
Why there is a hardcoded `bot.Token`? =)

### CODE REVIEW

**Comment by Syfaro** [comment]
I'm using the suggested path by the Telegram documentation. 

Also, your code shouldn't compile, `Url` should be all uppercase.

**Comment by gobwas** [comment]
@Syfaro hi! Sorry for the yesterday's late unclever PR, was too late for make it clear.
I've updated this PR, so now `ListenForWebhook` accepts `pattern string`.

So, answering in your comment about using suggested path by the Telegram spec -- it conflicts with the `SetWebhook` method, that accepts any webhook url, but current `ListenForWebhook` is sticked to the `"/"+bot.Token`. So there could be situation like:

```go

// here we setting webhook as some.host.com/blablabla
url := url.URL{... Path:"blablabla"}
bot.SetWebhook(WebhookConfig{URL: &url})

// but here we can not listen to it
bot.ListenForWebhook()
```

**Comment by Syfaro** [comment]
I think passing a string is the better solution, thanks for the PR :)

**Comment by gobwas** [comment]
:beers:

**Pull request merged**
